name: Build and deploy code

on:
  release:
    types: [published]
  workflow_dispatch:
  schedule:
    - cron: '41 6 * * *'


jobs:
  deploy:
    permissions:
        contents: read
        id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: lint
      run: |
        npm i
        npm run lint
    - name: build
      run: npm run build
    - name: Import Secrets
      uses: Infisical/secrets-action@v1.0.11
      with:
        method: "oidc"
        env-slug: "dev"
        project-slug: "github-g0zh"
        identity-id: "1ffe6b17-29ef-47ed-a54c-0912bbe40542"
    - name: Deploy prod
      if: ${{contains(github.ref, 'refs/tags/v')}}
      uses: ryand56/r2-upload-action@v1.4
      with:
        r2-account-id: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
        r2-access-key-id: ${{ env.R2_KEY_ID }}
        r2-secret-access-key: ${{ env.R2_KEY_SECRET }}
        r2-bucket: production
        source-dir: dist
        destination-dir: sdks/feedback
    - name: Deploy dev
      if: github.ref == 'refs/heads/main'
      uses: ryand56/r2-upload-action@v1.4
      with:
        r2-account-id: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
        r2-access-key-id: ${{ env.R2_KEY_ID }}
        r2-secret-access-key: ${{ env.R2_KEY_SECRET }}
        r2-bucket: production
        source-dir: dist
        destination-dir: sdks/dev/feedback
