name: lint code

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: install
      run: npm i
    - name: lint
      run: npm run lint
